- name: check Windows Updates
  hosts: '*windows_target'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    wsus_server: 192.168.1.52
    win_update_category_names:
      - CriticalUpdates
      - DefinitionUpdates
      - SecurityUpdates
      - UpdateRollups
      - Updates

  roles:
    - configure-update

  tasks:
    - block:
        - name: check for available updates.
          win_updates:
            category_names: "{{ win_update_category_names }}"
            state: searched
          register: available_updates

      rescue:
        - debug:
            msg: "{{ available_updates }}"
        - fail:
            msg: "fail here for now.."

- name: generate report
  hosts: '*windows_target'
  gather_facts: no

  tasks:
    - name: generate html report
      include_role:
        name: generate-update-report
      run_once: yes