- name: remove computer from wsus server
  hosts: all
  gather_facts: no
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    wsus_server: 192.168.1.36

  roles:
    - wsus-remove-computer