- name: install wsus server
  hosts: '*wsus_server'
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - wsus-server-configure