---

- name: stop windows update service
  win_service:
    name: "{{ item }}"
    state: stopped
  loop:
    - bits
    - wuauserv

- name: recreate update directory
  win_file:
    path: C:\Windows\SoftwareDistribution
    state: "{{ item }}"
  ignore_errors: yes
  loop:
    - absent
    - directory

- name: remove windows update settings
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate
    name: "{{ item }}"
    state: absent
  loop:
    - SusClientId
    - PingID
    - AccountDomainSid

- name: start windows update service
  win_service:
    name: "{{ item }}"
    state: started
  loop:
    - bits
    - wuauserv

- name: reset the windows update authorization
  win_command: wuauclt /resetauthorization /detectnow