---

- name: stop windows update service
  win_service:
    name: "{{ item }}"
    state: stopped
  loop:
    - bits
    - wuauserv

- name: remove windows update settings
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate
    name: "{{ item }}"
    state: absent
  loop:
    - SusClientId
    - PingID
    - AccountDomainSid

- name: start windows update service
  win_service:
    name: "{{ item }}"
    state: started
  loop:
    - bits
    - wuauserv

- name: reset windows update
  win_shell: wuauclt /resetauthorization /detectnow