---

- name: Install required DSC modules
  win_psmodule:
    name: "{{ item }}"
    state: present
  loop:
    - UpdateServicesDsc

- name: Install required WSUS server features
  win_dsc:
    resource_name: windowsfeature
    Name: "{{ item }}"
  loop:
    - UpdateServices
    - UpdateServices-WidDB
    - UpdateServices-Services
    - UpdateServices-RSAT
    - UpdateServices-API

- name: Ensure Content directory exists
  win_file:
    path: '{{ wsus_content_dir }}'
    state: directory

- name: Ensure WSUS server is deployed
  win_dsc:
    resource_name: UpdateServicesServer
    Ensure: Present
    ContentDir: '{{ wsus_content_dir }}'
    Languages: en
    Classifications:
      - "{{ category_names['CriticalUpdates'].id }}"
      - "{{ category_names['DefinitionUpdates'].id }}"
      - "{{ category_names['SecurityUpdates'].id }}"
      - "{{ category_names['ServicePacks'].id }}"
      - "{{ category_names['UpdateRollups'].id }}"
      - "{{ category_names['Updates'].id }}"
    Synchronize: True
    SynchronizeAutomatically: True
    SynchronizeAutomaticallyTimeOfDay: '01:30:00'

- name: Apply approval rules
  win_dsc:
    resource_name: UpdateServicesApprovalRule
    Name: "{{ category_names[item].name }}"
    Classifications: "{{ category_names[item].id }}"
    Enabled: True
    RunRuleNow: True
  loop:
    - CriticalUpdates
    - DefinitionUpdates
    - SecurityUpdates
    - ServicePacks
    - UpdateRollups
    - Updates

- name: Create automatic approval rule
  win_shell: |
    $WSUServer = Get-WsusServer
    if (-Not ($WSUServer.GetInstallApprovalRules() | Where {$_.Name -Eq "Default Automatic Approval Rule"})) {
        $WSUServer.CreateInstallApprovalRule("Default Automatic Approval Rule")
    }
  register: automatic_rule

- name: Enable automatic approval rule
  win_shell: |
    $WSUServer = Get-WsusServer
    $AutomaticRule = $WSUServer.GetInstallApprovalRules() | Where {$_.Name -Eq "Default Automatic Approval Rule"}
    $AutomaticRule.Enabled = $True
    $AutomaticRule.Save()
    $AutomaticRule.ApplyRule()
  when: automatic_rule.changed

- name: Clean up updates
  win_dsc:
    resource_name: UpdateServicesCleanup
    Ensure: Present
    DeclineExpiredUpdates: True
    DeclineSupersededUpdates: True
    CleanupObsoleteUpdates: True
    CleanupUnneededContentFiles: True