---

wsus_content_dir: C:\WSUS

category_names:
  CriticalUpdates:
    id: 'E6CF1350-C01B-414D-A61F-263D14D133B4'
    name: Critical Updates
  DefinitionUpdates:
    id: 'E0789628-CE08-4437-BE74-2495B842F43B'
    name: Definition Updates
  SecurityUpdates:
    id: '0FA1201D-4330-4FA8-8AE9-B877473B6441'
    name: Security Updates
  ServicePacks:
    id: '68C5B0A3-D1A6-4553-AE49-01D3A7827828'
    name: Service Packs
  UpdateRollups:
    id: '28BC880E-0592-4CBF-8F95-C79B17911D5F'
    name: Update Rollups Packs